name: Makefile CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install libudev
      run: sudo apt install libudev-dev

    - name: Run tests
      run: make test -f makefile 
      working-directory: ./cmd

    - name: Run build
      run: make build
      working-directory: ./cmd
