name: Makefile CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24'
    
    - name: Install dependencies
      run: go mod tidy

    - name: Create config
      run: |
        mkdir -p /tmp/configs
        cp configs/config_template.yaml configs/config.yaml
        cp configs/config_template.yaml /tmp/configs/config.yaml

    - name: Run tests
      run: make test -f makefile
      working-directory: ./cmd

    - name: Run build
      run: make build
      working-directory: ./cmd
    
    - name: Run tests with coverage
      run: go test -coverprofile=coverage.out ./...
