name: Makefile CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create config
      run: mkdir -p /tmp/configs && cp configs/config_template.yaml configs/config.yaml && cp configs/config_template.yaml /tmp/configs/config.yaml # adding /tmp/configs/config.yaml but it's caused by a bug, make test cannot get the config from <project_root>/configs/config.yaml 

    - name: Run tests
      run: make test -f makefile 
      working-directory: ./cmd

    - name: Run build
      run: make build
      working-directory: ./cmd
